# numpy practice session

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
# import tgis library in j.notebook
import numpy as np


# Creating an array using numpy

In [3]:
food=np.array (["pakora", "samosa", "raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [4]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [5]:
type(price)

numpy.ndarray

*ndarray..... n number of dimensional array*

In [6]:
type(food)

numpy.ndarray

In [7]:
len(food)

3

In [8]:
len(price)

3

In [9]:
price[2]

5

In [10]:
price[0]

5

In [11]:
food[0]

'pakora'

In [12]:
# 0 se start hy likin figure 3 he likhne hy
food[0:3]
     

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [13]:
# Different function array
price.mean()


5.0

In [14]:
# zeros method
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
# ones
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
# empty
np.empty(5)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 9.12209163e-312,
       3.56050862e-307])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [19]:
# specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
# specify interval
np.arange(4,100,10)

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [21]:
# table
np.arange(0,55,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [22]:
# table
np.arange(0,44,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [23]:
# line space
np.linspace(0,10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
# line space
np.linspace(0,40, num=5)

array([ 0., 10., 20., 30., 40.])

In [25]:
# linepsace (with same interval yni barabri ka gap)
np.linspace(0,50, num=5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [26]:
# line space( same distance between numbers)
np.linspace(0,10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
#  specify your data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [28]:
#  specify your data type
np.ones(50, dtype=np.int16)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int16)

##  Array FunctionFunctions 

In [29]:
a=np.array([10,12,15,2,4,100,320,0.5,10.4])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. , 100. , 320. ,   0.5,  10.4])

In [30]:
# acesending order
a.sort()
a

array([  0.5,   2. ,   4. ,  10. ,  10.4,  12. ,  15. , 100. , 320. ])

In [31]:
b=np.array([10.2, 3.4, 53.6, 91.4,45.4])
b

array([10.2,  3.4, 53.6, 91.4, 45.4])

In [32]:
c=np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,  10. ,  10.4,  12. ,  15. , 100. , 320. ,
        10.2,   3.4,  53.6,  91.4,  45.4])

In [33]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,  10. ,  10.2,  10.4,  12. ,  15. ,
        45.4,  53.6,  91.4, 100. , 320. ])

##  2-d arrays


## concatinate of same d or sizesm

In [34]:
   a=np.array([[1,2,3,4],[5,4,3,2]])
a

array([[1, 2, 3, 4],
       [5, 4, 3, 2]])

In [35]:
b=np.array([[6,7,4,5],[8,5,5,9]])
b

array([[6, 7, 4, 5],
       [8, 5, 5, 9]])

In [36]:
c=np.concatenate((a,b))
c

array([[1, 2, 3, 4],
       [5, 4, 3, 2],
       [6, 7, 4, 5],
       [8, 5, 5, 9]])

## concatenate of different D or sizes

In [37]:
a=np.array([[1,2,3,4],[5,4,3,2]])
a

array([[1, 2, 3, 4],
       [5, 4, 3, 2]])

In [38]:
b=np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [39]:
c=np.concatenate((a,b), axis=1)
c

array([[1, 2, 3, 4, 5, 6],
       [5, 4, 3, 2, 7, 8]])

## concatinate of axis=0

In [40]:
a=np.array([[2,1],[7,3]])
a


array([[2, 1],
       [7, 3]])

In [41]:
b=np.array([[4,2],[5,6]])
b

array([[4, 2],
       [5, 6]])

In [42]:
c=np.concatenate((a,b), axis=0)
c

array([[2, 1],
       [7, 3],
       [4, 2],
       [5, 6]])

In [43]:
c=np.concatenate((a,b), axis=1)
c

array([[2, 1, 4, 2],
       [7, 3, 5, 6]])

##  concatenate of axis=1

In [44]:
a=np.array([[2,1,3],[7,3,4]])
a


array([[2, 1, 3],
       [7, 3, 4]])

In [45]:
b=np.array([[4,2],[5,6]])
b

array([[4, 2],
       [5, 6]])

In [46]:
c=np.concatenate((a,b), axis=1)
c

array([[2, 1, 3, 4, 2],
       [7, 3, 4, 5, 6]])

In [47]:
# c=np.concatinate((a,b), axis=0) it can't be stack


### 3-D ( 2d in one etc is also called TASERFLOW

In [94]:
a=np.array([[[11,2,3,4],[3,4,5,6]],
           [[4,5,6,7],[5,2,3,1]],
           [[5,9,6,3],[9,6,5,3]]])
a
          

array([[[11,  2,  3,  4],
        [ 3,  4,  5,  6]],

       [[ 4,  5,  6,  7],
        [ 5,  2,  3,  1]],

       [[ 5,  9,  6,  3],
        [ 9,  6,  5,  3]]])

In [49]:
a.size

24

In [50]:
a.shape

(3, 2, 4)

- (3,2,4) 3 means 3d, 2 means rows, 4 columns

In [51]:
# to find the number of dimensions
a.ndim

3

In [52]:
type(a)

numpy.ndarray

##  3 by 3 matrix is 2 dimension arraym

In [68]:
b=np.array([[5,4,3],[5,3,7],[4,7,5]])
b

array([[5, 4, 3],
       [5, 3, 7],
       [4, 7, 5]])

In [65]:
b.size

9

In [66]:
b.shape

(3, 3)

In [54]:
b.ndim

2

In [55]:
b=np.array([[[5,4,3],[5,3,7],[4,7,5]],
           [[5,4,3],[5,3,7],[4,7,5]]])
b

array([[[5, 4, 3],
        [5, 3, 7],
        [4, 7, 5]],

       [[5, 4, 3],
        [5, 3, 7],
        [4, 7, 5]]])

In [56]:
b.size

18

In [57]:
b.shape

(2, 3, 3)

In [58]:
b.ndim

3

In [59]:
b=np.array([4,5,6])
b.ndim

1

## HINT
- agr 3 blocks me bnd mtrix hoga to 3d
- agr 2 block me bnd mtrix hoga to b 3d
- age ak block me bnd hoga tb 2d
- agr simple ak he axis ho to 1D

In [60]:
#  size (number of elements)
a.size

24

In [95]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [97]:
#  reshape
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [133]:
b=np.arange(9)   # 3*3=9
b.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [139]:
b=np.arange(64)     #8*8=64
b.reshape(8,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [165]:
# reshape
a=np.array([[1,2,3],[6,7,8],[5,2,5]])
np.reshape(a,newshape=(1,9), order="C")

array([[1, 2, 3, 6, 7, 8, 5, 2, 5]])

###  convert 1d into 2d
- [np.newaxis, :]

In [166]:

a=np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [167]:
a.shape

(8,)

### shape change


In [171]:
b=a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [172]:
b.shape


(1, 8)

### Dimensional change
### row wise 2d conversion

In [174]:
c=a[np.newaxis,:]
c

array([[1, 2, 3, 4, 5, 6, 7, 8]])

### column wise 2d conversion

In [175]:
d=a[:,np.newaxis]
d

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

### indexes

In [179]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [181]:
a[1:6]

array([2, 3, 4, 5, 6])

In [182]:
a[2:6]

array([3, 4, 5, 6])

In [187]:
a[2:8]

array([3, 4, 5, 6, 7, 8])

In [188]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48])

In [189]:
a


array([1, 2, 3, 4, 5, 6, 7, 8])

In [190]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48])

In [191]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [194]:
a.sum()

36

In [195]:
a.mean()

4.5