In [2]:
import numpy as np
a=np.array([5,5,5,5,5,5])
a

array([5, 5, 5, 5, 5, 5])

### 1-Dimensional array

In [4]:
import numpy as np
a=np.array([5,5,5,])
a

array([5, 5, 5])

In [23]:
len(a)

3

In [25]:
a[0]

5

In [26]:
a[0:3]

array([5, 5, 5])

In [27]:
a[0:2]

array([5, 5])

### - ndarray means N number of dimention

In [5]:
type(a)

numpy.ndarray

###  2-Dimensional array (row. colomn)

In [10]:
#  list of lists
b=np.array([[5,5,5],[5,5,5],[5,5,5]])
b


array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [24]:
len(b)

3

In [18]:
# importing the module
import numpy as np

d1=np.array([4,5,6,7])
d1


array([4, 5, 6, 7])

In [19]:
d2=np.array([[3,5,8,2],[3,4,7,5],[7,6,5,4]])
d2

array([[3, 5, 8, 2],
       [3, 4, 7, 5],
       [7, 6, 5, 4]])

### 1-Dimensional array is called vector
### (there is no difference between row and column in 1-D)
### 2-Dimensional is called matrix
### 3-ndarray is used for both matrix and vector

## Vector is 1-D
## matrix is 2-D
## "array" can mean either a single-dimensional array, or a multidimensional array